import Head from 'next/head'
import Hero from './components/Hero'
import Navbar from './components/Navbar'
import Portfolio from './components/Portfolio'
import Technologies from './components/Technologies'

export default function Home() {
  return (
    <>
      <Head>
        <title>Juan Galué portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='bg-white px-5 md:px-20 lg:px-40 dark:bg-[#101827]'>
        <section className='min-h-screen'>
          <Navbar />
          <Hero />
          <Technologies />
          <Portfolio />
        </section>
      </main>
    </>
  )
}
